name: ItemID
authors: ['MariusB', 'Primus']
main: MariusB\ItemID\Main
version: 1.0.0
api: 1.5.0

commands:
    item:
        description: "Identifies item in hand"

permissions:
    item.command:
        description: "Players with this permission are able to run /item command"
        default: true
    item.info:
        description: "Get ItemID in Hotbar"
        default: OP
